import { Vault, Transaction, Contact } from '../types/vault';

export const INITIAL_AVAILABLE_BALANCE = 12450;

export const DEFAULT_USER = {
  name: 'Siri',
  handle: '@siri',
  upiId: 'siri@vautly',
  phone: '+91 98765 43210',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
};

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: 'c-1',
    name: 'Ananya Sharma',
    upiId: 'ananya@vautly',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
    phone: '+91 98123 45678',
    recent: true,
  },
  {
    id: 'c-2',
    name: 'Rahul Verma',
    upiId: 'rahul@vautly',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    phone: '+91 97654 32109',
    recent: true,
  },
  {
    id: 'c-3',
    name: 'Sai Reddy',
    upiId: 'sai@vautly',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    phone: '+91 99887 76655',
    recent: true,
  },
  {
    id: 'c-4',
    name: 'Priya Nair',
    upiId: 'priya@vautly',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=120&auto=format&fit=crop&q=80',
    phone: '+91 91234 56789',
    recent: true,
  },
  {
    id: 'c-5',
    name: 'Vikram Mehta',
    upiId: 'vikram@vautly',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
    phone: '+91 98765 12345',
    recent: false,
  },
  {
    id: 'm-1',
    name: 'ABC Store',
    upiId: 'abcstore@upi',
    avatar: '🛍️',
    isMerchant: true,
    recent: true,
  },
  {
    id: 'm-2',
    name: 'Coffee House',
    upiId: 'coffeehouse@upi',
    avatar: '☕',
    isMerchant: true,
    recent: true,
  },
  {
    id: 'm-3',
    name: 'Tech Accessories Hub',
    upiId: 'techhub@upi',
    avatar: '🎧',
    isMerchant: true,
    recent: false,
  },
];

export const INITIAL_VAULTS: Vault[] = [
  {
    id: 'vault-laptop',
    title: 'Laptop Fund',
    icon: '💻',
    color: '#3B82F6', // Blue
    reservedAmount: 2450,
    targetAmount: 3500,
    targetDate: '2026-12-15',
    category: 'essential',
    notes: 'M3 MacBook Pro upgrade fund',
    isArchived: false,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'vault-vacation',
    title: 'Vacation',
    icon: '✈️',
    color: '#EC4899', // Pink
    reservedAmount: 4200,
    targetAmount: 6500,
    targetDate: '2026-11-20',
    category: 'dream',
    notes: 'Goa beach getaway and resort reservation',
    isArchived: false,
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'vault-pet',
    title: 'Pet Care',
    icon: '🐶',
    color: '#F59E0B', // Amber
    reservedAmount: 2450,
    targetAmount: 3000,
    targetDate: '2027-01-10',
    category: 'lifestyle',
    notes: 'Veterinary care, premium food & insurance',
    isArchived: false,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'vault-emergency',
    title: 'Emergency Fund',
    icon: '🛡️',
    color: '#10B981', // Emerald
    reservedAmount: 15000,
    targetAmount: 25000,
    targetDate: '2027-06-30',
    category: 'essential',
    notes: 'Safety net for unforeseen health and liquid cash needs',
    isArchived: false,
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'vault-education',
    title: 'Education',
    icon: '🎓',
    color: '#8B5CF6', // Purple
    reservedAmount: 8000,
    targetAmount: 12000,
    targetDate: '2026-10-15',
    category: 'growth',
    notes: 'Advanced system design & AI certifications',
    isArchived: false,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'vault-shopping',
    title: 'Shopping & Gear',
    icon: '🛍️',
    color: '#6366F1', // Indigo
    reservedAmount: 1800,
    targetAmount: 4000,
    targetDate: '2026-11-01',
    category: 'lifestyle',
    notes: 'Festive season apparel & smart home accessories',
    isArchived: false,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-101',
    txId: 'VTL-829103',
    recipientName: 'ABC Store',
    recipientUpiId: 'abcstore@upi',
    amount: 450,
    type: 'sent',
    paymentSource: 'Vautly Balance',
    paymentSourceId: 'available',
    description: 'Payment to ABC Store',
    note: 'Weekly essentials & snacks',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    status: 'successful',
  },
  {
    id: 'tx-102',
    txId: 'VTL-712904',
    senderName: 'Rahul Verma',
    senderUpiId: 'rahul@vautly',
    amount: 2000,
    type: 'received',
    toTitle: 'Vautly Balance',
    description: 'Received from Rahul Verma',
    note: 'Dinner bill split repayment',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    status: 'successful',
  },
  {
    id: 'tx-103',
    txId: 'VTL-654129',
    recipientName: 'Coffee House',
    recipientUpiId: 'coffeehouse@upi',
    amount: 200,
    type: 'sent',
    paymentSource: 'Vautly Balance',
    paymentSourceId: 'available',
    description: 'Payment to Coffee House',
    note: 'Artisanal cold brew & croissants',
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'successful',
  },
  {
    id: 'tx-104',
    txId: 'VTL-543210',
    vaultId: 'vault-laptop',
    vaultTitle: 'Laptop Fund',
    amount: 750,
    type: 'transfer',
    fromTitle: 'Vautly Balance',
    toTitle: 'Laptop Fund',
    description: 'Saved to Laptop Fund',
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'successful',
  },
  {
    id: 'tx-105',
    txId: 'VTL-432109',
    recipientName: 'Ananya Sharma',
    recipientUpiId: 'ananya@vautly',
    amount: 350,
    type: 'sent',
    paymentSource: 'Vacation Vault',
    paymentSourceId: 'vault-vacation',
    description: 'Payment to Ananya Sharma',
    note: 'Goa travel deposit share',
    timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'successful',
  },
];

